### ISSUE TITLE
It's Not Working in Magento 1.9.X

### ISSUE THREAD

**Issue by himansuahm** [progammer-rkt/Rkt_SbCache#5]
I try to add this observers in my module and than after install full module but it's not working.

**Comment by rajeev-k-tomy** [comment]
@himansuahm Could you please specify exact version of your Magento instance ? Because this issue is already fixed in latest releases. You don't need to use this module in that case.

**Comment by himansuahm** [comment]
Magento CE 1.9.2.4.
I create new block for sub category from template and call that in magento category block.

**Comment by zigojacko** [comment]
Issue still apparent in 1.9.2.4 but this fix does not resolve in this version.

**Comment by rajeev-k-tomy** [comment]
Please follow [**this thread**](https://github.com/progammer-rkt/Rkt_SbCache/issues/7) for more details
